### ISSUE TITLE
cant see dns log on dns.1433.eu.org

### ISSUE THREAD

**Issue by shino-337** [f0ng/log4j2burpscanner#1]
![image](https://user-images.githubusercontent.com/8822078/145673187-fba7d6e9-72c7-478c-83a2-4d847bd70d9a.png)

I tried using your extension to double check on domain test, but can't see dns record and error message.

**Comment by f0ng** [comment]
thankx，I forgot to update it,it should be "https://log.xn--9tr.com/" append your token
0.11 fix it
![image](https://user-images.githubusercontent.com/48286013/145673598-7ce79af0-f321-413b-8c91-c119ad2f90d6.png)
