### ISSUE TITLE
额外的触发点

### ISSUE THREAD

**Issue by youyhyhyh** [f0ng/log4j2burpscanner#12]
包头里各种 Content-Type、Referer、Accept-Language、Accept、Accept-Encoding等都有可能成为触发点，望加入检测范围，感谢。

**Comment by f0ng** [comment]
感谢反馈，将在下个版本更新、优化

**Comment by youyhyhyh** [comment]
嗯，后续手测时有发现，有些站又会因为修改上面提到的个别字段而报错，反而影响结果，请关注一下，感谢。个人想法是让这几个字段作为一个分组，以一个增量的形式二次发包检测，这样不影响之前脚本的检测结果。

**Comment by f0ng** [comment]
下个版本增加参数可控，二次发包后续会去考虑

**Comment by f0ng** [comment]
`0.15`版本已经更新
