### ISSUE TITLE
新版本dnslog配置问题

### ISSUE THREAD

**Issue by Chinakentgao** [f0ng/log4j2burpscanner#18]
0.15 burp第一次加载后dnslog部分dnsldaprmi=dns出现了两次，应该是写重了吧。小问题删掉一个保存就行，就是不知道并存的话优先级最高的是哪个 哈哈

**Comment by f0ng** [comment]
感谢师傅，确实是，写多了一个，`0.15.1`版本已经改好了

**Comment by Chinakentgao** [comment]
我在测试掌控的靶场，插件没检测出来还不知道什么问题。http://d63bb2586.lab.aqlab.cn/ 你试试看 我这边要上班暂时没办法测试




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月15日(星期三) 上午10:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [f0ng/log4j2burpscanner] 新版本dnslog配置问题 (Issue #18)





 
感谢师傅，确实是，写多了一个，0.15.1版本已经改好了
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Chinakentgao** [comment]
我测试了下可以检测出来，是我同事操作问题你忽略上封邮件


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "f0ng/log4j2burpscanner"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月15日(星期三) 上午10:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [f0ng/log4j2burpscanner] 新版本dnslog配置问题 (Issue #18)





 
感谢师傅，确实是，写多了一个，0.15.1版本已经改好了
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by f0ng** [comment]
好的，那就关闭了
