### ISSUE TITLE
内网dnslog平台要怎么配置？

### ISSUE THREAD

**Issue by littleheary** [f0ng/log4j2burpscanner#19]
比如我本地开启了xray的反连，我应该怎么配置响应url那里？

**Comment by f0ng** [comment]
xray没有相应的api响应接口，目前是不支持的，但是如果只是想探测漏洞，在本地查看响应的从而确认漏洞的话，可以这么配置
isprivatedns=true
privatednslogurl=[xray反连平台地址]
privatednsResponseurl=xxxx

**Comment by f0ng** [comment]
可查看最新[README](https://github.com/f0ng/log4j2burpscanner/blob/main/README.md)进行内网dnslog配置
