### ISSUE TITLE
刚发现的问题

### ISSUE THREAD

**Issue by Chinakentgao** [f0ng/log4j2burpscanner#20]
靶场就刚才我邮件发你的那个，我配置了ceye.io的域名dns收到请求了但是插件没有提示有漏洞。图片我通过邮件发你了。还有采用默认的dnslog就检测到一次，接来下全部都没有检测出来。具体原因不清楚可能需要你自测一下。我邮箱把图片发你，你看看。

**Comment by f0ng** [comment]
jtsqrj@gmail.com

**Comment by Chinakentgao** [comment]
发你这个邮箱了你看下我的截图




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月15日(星期三) 中午11:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [f0ng/log4j2burpscanner] 刚发现的问题 (Issue #20)





 
***@***.***
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by f0ng** [comment]
确实有，因为ceye的filter参数长度超过20就会报错，感谢反馈，`0.15.2`已修复该问题
