### ISSUE TITLE
新版本的payload搞错了吧😅

### ISSUE THREAD

**Issue by m82a3** [f0ng/log4j2burpscanner#22]
![dns.png](https://s2.loli.net/2021/12/15/uMHpCaQGZ96NrBP.png)

**Comment by m82a3** [comment]
![new.png](https://s2.loli.net/2021/12/15/wXF9vzZ6PoNAkxn.png)
上面是15.2，最新版15.3更奇怪，难道是我这边的问题？

**Comment by f0ng** [comment]
建议师傅去看下README或者FAQ，我这边测试没问题的
应该是配置没更新，去恢复默认配置界面获取最新参数
![image](https://user-images.githubusercontent.com/48286013/146156394-79d2f43d-b520-4e29-a9ad-6587035e334e.png)

**Comment by m82a3** [comment]
> 建议师傅去看下README或者FAQ，我这边测试没问题的 应该是配置没更新，去恢复默认配置界面获取最新参数 ![image](https://user-images.githubusercontent.com/48286013/146156394-79d2f43d-b520-4e29-a9ad-6587035e334e.png)

OK了，我的原因， 旧版本的配置文件冲突了，谢谢
