### ISSUE TITLE
关于数据包中多个参数同时被替换

### ISSUE THREAD

**Issue by k-fire** [f0ng/log4j2burpscanner#23]
插件目前应该是一次性替换所有请求吧？的确可以减少发包的数量。
结果遇到个问题，漏洞点在waf上，但是一个包中所有参数同时被替换结果触发不了，只有当单独某一个参数为payload才能触发。
还有就是，当勾选header其他参数测试时，原数据包本来不存在的参数被添加，造成请求异常等等

**Comment by f0ng** [comment]
感谢反馈，问题1有考虑到，后续会优化；问题2的话，预计下个版本会优化

**Comment by f0ng** [comment]
问题2，`0.16.5`已优化

**Comment by f0ng** [comment]
问题1，`0.16.6`已优化，具体为增加一个请求，原因为某些uri里的参数可能为路由参数，所以增加一个正常uri，但是携带其他headers头payload的请求
