### ISSUE TITLE
UI问题

### ISSUE THREAD

**Issue by chenchenhen6** [f0ng/log4j2burpscanner#24]
师傅，我这每次打开burp都是这样的
![image](https://user-images.githubusercontent.com/35289748/146327875-98c8eb21-67c6-4671-8e53-bef382c540ef.png)

**Comment by f0ng** [comment]
感谢反馈，原因应该在于jdk对ui的适配问题，可以手动拖动此处
![image](https://user-images.githubusercontent.com/48286013/146328309-53425769-3bdb-46fe-991d-fd571a3b0271.png)

**Comment by chenchenhen6** [comment]
![image](https://user-images.githubusercontent.com/35289748/146329225-a59411c5-d84b-4b19-a4db-be517dd4b360.png)
之前的版本好好的，不会这样

**Comment by f0ng** [comment]
可能有些参数的问题，还麻烦师傅反馈一下新版`0.16.5`试试呢，UI是个头疼问题

**Comment by chenchenhen6** [comment]
依然是这样，师傅

**Comment by f0ng** [comment]
师傅`0.16.5.1`版本再看看呢，这里设置了分割线，在旧版本bp也试了下，是和之前插件版本一样，页面正常的

**Comment by chenchenhen6** [comment]
师傅，0.16.5.1没问题

**Comment by f0ng** [comment]
OK，那就关闭了
