### ISSUE TITLE
网站执行太慢好像会检测不出

### ISSUE THREAD

**Issue by qawsedc** [f0ng/log4j2burpscanner#25]
如图，已经回显成功了，但是响应速度不是很快，插件则没有检测出。
![png](https://user-images.githubusercontent.com/44834591/146370536-98563531-2329-440f-95bd-d6679dd28811.png)

**Comment by f0ng** [comment]
感谢师傅反馈。对的，存在延迟会导致检测不出来，目前没办法避免该类问题

**Comment by qawsedc** [comment]
好的，那就直接去web上看算了。感谢师傅的插件

**Comment by f0ng** [comment]
最好是能找到与当前网络环境较快的dnslog，可以去自定义模块修改，不然按照目前来说，还是蛮难解决这个问题的
再次感谢师傅反馈，如果有问题，请重新提交issue！
