### ISSUE TITLE
可以增加一个随机的字符串标记吗？

### ISSUE THREAD

**Issue by k-fire** [f0ng/log4j2burpscanner#29]
我发现有些网站请求地址太长而导致都是一样的 没法定位到某个具体参数，可不可以增加一个随机的字符串标记以便定位

**Comment by f0ng** [comment]
感谢师傅反馈，参数点已经用数字标记出来了，详情可以看到DNSLOG的第一位数字参数

![image](https://user-images.githubusercontent.com/48286013/146639306-fa7b0a3e-30cb-472c-abfb-c0e944b94c6a.png)

**Comment by k-fire** [comment]
> 感谢师傅反馈，参数点已经用数字标记出来了，详情可以看到DNSLOG的第一位数字参数
> 
> ![image](https://user-images.githubusercontent.com/48286013/146639306-fa7b0a3e-30cb-472c-abfb-c0e944b94c6a.png)

我知道有这个，我的意识是后面GET.127.0.0.1.路径.路径 这些很容易重复，这样即使是0 1 2 前缀也是会有一堆一样的请求

**Comment by f0ng** [comment]
好的，下个版本进行优化

**Comment by k-fire** [comment]
> 好的，下个版本进行优化

感谢

**Comment by f0ng** [comment]
`0.17`版本已优化该问题
