### ISSUE TITLE
在最新的版本中dns协议是生效的，但是payload没有处理好，从log4j打印的日志来看，payload多了1个点

### ISSUE THREAD

**Issue by purple-WL** [f0ng/log4j2burpscanner#3]
![image](https://user-images.githubusercontent.com/63894044/145702364-62400138-38b5-4dd4-8d26-f780d04895fa.png)
这使dns log收不到请求

**Comment by f0ng** [comment]
感谢反馈，在最新的0.11版本已经修复过了这个问题，师傅下载最新版本试试呢，其实刚发出来我就发现了，然后马上又把0.11的jar改了重新发了一次
