### ISSUE TITLE
没有回复信息

### ISSUE THREAD

**Issue by e0mlja** [f0ng/log4j2burpscanner#31]
![image](https://user-images.githubusercontent.com/50048558/146723163-d4cde9d1-4d76-43e8-bb43-060f131bd99a.png)
![image](https://user-images.githubusercontent.com/50048558/146723285-019328ef-68e3-4b0f-80f7-205ed0895e6e.png)

加载成功了，但是没任何相应

**Comment by e0mlja** [comment]
没有任何响应，重放过去也不行

**Comment by f0ng** [comment]
这里是有漏洞才会显示数据包的，默认是被动扫描，可以去logger模块查看被动扫描日志，也可以在数据包右键`Send to log4j2 Scanner`

**Comment by e0mlja** [comment]
主要就是send to log4j2 Scanner  也没有反应

**Comment by f0ng** [comment]
`logger`模块没有扫描日志吗，还有就是白名单设置问题，站点在白名单里的话是不会扫的

**Comment by Polaris-L** [comment]
我也是同样的问题，用的jdk11的jar包，无扫描日志，白名单也没配置，右键send to 到插件中也没响应

**Comment by f0ng** [comment]
可以点击按钮`test dnslog delay`测试下你的环境，如果没有配置ceye和自定义dnslog的话，会使用默认dnslog，但是默认dnslog有时会加载不出来，就会导致不进行扫描
![image](https://user-images.githubusercontent.com/48286013/146891632-c61c3e51-1af3-4311-b213-8633f89dc987.png)
![image](https://user-images.githubusercontent.com/48286013/146891638-c1d292f3-911b-4716-a362-a011df981bfb.png)

**Comment by Polaris-L** [comment]
我配置了ceye，测试结果如下：
![image](https://user-images.githubusercontent.com/39089928/146893303-02fa89ea-6fe4-41dc-bbe2-9bb0d47e8b44.png)

**Comment by f0ng** [comment]
师傅发下联系方式到jtsqrj@gmail.com吧，我来私聊看看

**Comment by himay1** [comment]
我也是这个问题

**Comment by Polaris-L** [comment]
> 我也是这个问题

你也用的mac吗

**Comment by f0ng** [comment]
咱三都是mac

**Comment by f0ng** [comment]
[FAQ](https://github.com/f0ng/log4j2burpscanner/blob/main/FAQ-zh-CN.md#10-%E4%B8%BA%E4%BB%80%E4%B9%88%E6%89%AB%E6%8F%8F%E6%B2%A1%E6%9C%89%E5%8A%A8%E9%9D%99)
