### ISSUE TITLE
插件不生效

### ISSUE THREAD

**Issue by himay1** [f0ng/log4j2burpscanner#32]
加载插件后配置好配置，但是在截取数据包的过程中没有被动扫描log4j

**Comment by f0ng** [comment]
开启`passive scanner`了吗，接口继承`passive`的

**Comment by f0ng** [comment]
师傅发下联系方式到jtsqrj@gmail.com吧，我私聊看看

**Comment by f0ng** [comment]
[FAQ](https://github.com/f0ng/log4j2burpscanner/blob/main/FAQ-zh-CN.md#10-%E4%B8%BA%E4%BB%80%E4%B9%88%E6%89%AB%E6%8F%8F%E6%B2%A1%E6%9C%89%E5%8A%A8%E9%9D%99)

**Comment by himay1** [comment]
![image](https://user-images.githubusercontent.com/40022484/146957747-01a5ae80-6165-449a-9c21-2afae04d3288.png)
还是不可以

**Comment by himay1** [comment]
这么配置完了以后还是不行

**Comment by f0ng** [comment]
g了，这个和jdk有关的，昨天加了一个师傅，把jdk改回来就行了
这是jdk下载网站，比较快的 https://repo.huaweicloud.com/java/jdk/

**Comment by himay1** [comment]
我用的jdk版本是1.8为啥也不行

**Comment by f0ng** [comment]
1.8_231

**Comment by f0ng** [comment]
这个问题出在jdk版本问题，burp的java environment设置为1.8_231(这里测试是可以的)，测试与启动burp的版本无关，但是如果burp的java environment没有设置，将会自动设置为启动burp的jdk版本
如果还不行再进行反馈，过高过低都不行

**Comment by himay1** [comment]
我找了下1.8 只找到311的了 231的找不到。。如果有可以提供我试试，现在311的不行

**Comment by f0ng** [comment]
联系方式发到jtsqrj@gmail.com了吗
