### ISSUE TITLE
提两个建议

### ISSUE THREAD

**Issue by taiwuliao** [f0ng/log4j2burpscanner#34]
第一个是建议添加一个对请求头的参数都进行测试的功能，因为在使用过程中发现有些请求头并不在选项里面，但是是有漏洞的，比如vulfocus靶场新加了一个x-api-version的请求头存在漏洞，但是插件不扫描。
第二个是判断依据的问题，我在测试靶场这个参数的时候，发现其它参数存在漏洞有dnslog回显，但是响应包是406，结果就不报这个漏洞点。

**Comment by f0ng** [comment]
第一个建议主要是重在收集，默认情况下xff、xci、if-modified-since这些都会加上，感谢师傅反馈这个参数，预计下版本更新，但是在一些情况下，请求头多了，会造成服务器无法响应
第二个建议，本工具主要是看dnslog平台的响应，不会去看数据包的响应包，师傅所说的这种情况，应该是出在与dnslog平台响应的问题上，有延迟导致这种情况的发生

**Comment by taiwuliao** [comment]
我使用的是ceye的平台

**Comment by f0ng** [comment]
可以点击`test dnslog delay`按钮看看延迟

**Comment by taiwuliao** [comment]
在90ms左右

**Comment by f0ng** [comment]
师傅联系方式发到jtsqrj@gmail.com吧，我私聊看看

**Comment by f0ng** [comment]
建议1已在`0.17.4`版本更新
