### ISSUE TITLE
为什么右键按钮Send to log4j2 Scanner后插件界面是空的，好像就没有扫描

### ISSUE THREAD

**Issue by 0greatary** [f0ng/log4j2burpscanner#36]
为什么右键按钮Send to log4j2 Scanner后插件界面是空的，好像扫描失效，试了很多次还是这样，求解答～

**Comment by f0ng** [comment]
[FAQ](https://github.com/f0ng/log4j2burpscanner/blob/main/FAQ-zh-CN.md#10-%E4%B8%BA%E4%BB%80%E4%B9%88%E6%89%AB%E6%8F%8F%E6%B2%A1%E6%9C%89%E5%8A%A8%E9%9D%99)

**Comment by 0greatary** [comment]
我按照FAQ里面 更改为 jdk1.8.0_181.jdk 版本也是不行也

**Comment by f0ng** [comment]
231或者151，不行的话，我也没办法了，我这边测试正常，只可能与jdk环境有关

**Comment by 0greatary** [comment]
加载的是 log4j2burpscanner-0.17.6-jdk8插件。burp里面Java Environment文件夹也更换成jdk1.8.0_181.jdk   还是不行
 是不是我得我这边自行编译 就可能ok？

**Comment by f0ng** [comment]
有可能，看FAQ吧
