### ISSUE TITLE
关于优化建议

### ISSUE THREAD

**Issue by Chinakentgao** [f0ng/log4j2burpscanner#4]
1.payload的请求设定建议在每个payload上加入数字顺序。意思就是比如包里有5处可以插件自动化输入payload的地方，那么5个参数的payload可以是test1.XXX.ceye.io依次到test5.XXX.ceye.io的方式。这样在查看ceye.io log的时候就知道是哪个payload触发了漏洞方便定位数据包中的漏洞点。
2.能否增加一个内网检测的参数进行切换可以修改自定义的请求rmi和ldap的地址，用于快速检测内网不出网资产的漏洞验证。利用插件帮忙自动化输入到参数进行测试可以节省很多时间。
这几天漏洞爆发很多业主单位都要求排查漏洞所以这个需求还是很关键的。

**Comment by Chinakentgao** [comment]
> 1.payload的...
补充下一个疑问请求payload加入这么多参数会不会导致原始请求出现问题，之前用过一个请求头伪造IP的添加这么多导致正常请求都报错了。所以加这么多头部注入如果可以请新增一个开关功能来限制是否开启。

**Comment by f0ng** [comment]
感谢师傅反馈，三个问题将在下个版本进行更新，优化

**Comment by f0ng** [comment]
新版本已经优化
