### ISSUE TITLE
custom header lists请求异常

### ISSUE THREAD

**Issue by 9uoer** [f0ng/log4j2burpscanner#42]
custom header lists置空，依然会有jndi payload出现在请求报文里，导致请求异常

**Comment by f0ng** [comment]
感谢师傅反馈，问题出在自定义参数置为空后，由于只判断了长度，所以依然会添加空的值payload，造成请求异常，将在下版本修复

**Comment by f0ng** [comment]
`0.18.4`版本修复该问题
