### ISSUE TITLE
右键发送log4j2问题

### ISSUE THREAD

**Issue by nniujun** [f0ng/log4j2burpscanner#48]
大佬，右键发送log4j2没有反应，看到了您对其他人的回复，测试了您所使用的jdk版本，也存在同样的问题，盼复。

**Comment by f0ng** [comment]
试试只装本插件右键发送log4j2，有可能是插件之间的冲突

**Comment by nniujun** [comment]
只装了这个插件，其他没有装的，burp版本是2.1


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: f0ng ***@***.***&gt;
发送时间: 2022年4月21日 22:36
收件人: f0ng/log4j2burpscanner ***@***.***&gt;
抄送: nniujun ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[f0ng/log4j2burpscanner] 右键发送log4j2问题 (Issue #48)





 
试试只装本插件右键发送log4j2，有可能是插件之间的冲突

**Comment by f0ng** [comment]
方便的话加下微信，f-f0ng

**Comment by f0ng** [comment]
问题出现在参数配置上面，已解决
