### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by Teicu** [f0ng/log4j2burpscanner#57]
Hi 

Can it be used with Burp Collaborator or canarytokens.com? If not, then can you implement those too please? 

Thanks

**Comment by f0ng** [comment]
Hello
Sorry,Burp Collaborator has too high latency,so I don't plan to support it
In fact,at present, as long as the DNS platform requested through the "GET" method is supported

**Comment by f0ng** [comment]
By the way,canarytokens.com seems that it only supports the source of the IP address and does not support the specific content of the request
