### ISSUE TITLE
使用完整的域名做标识符会将冒号“:”带入导致域名出现错误

### ISSUE THREAD

**Issue by 0xWi11** [f0ng/log4j2burpscanner#58]
如果说测试目标为 http://example.com:1234 那么payload中会出现 ``http:`` 和 ``:1234`` 导致最后生成的URL为非法的格式如图。
![QQ截图20230210213919](https://user-images.githubusercontent.com/44541702/218106629-e3a583b8-0894-4238-a2d6-cc2b69f4c084.jpg)

ping 命令无法识别最后生成的域名
![image](https://user-images.githubusercontent.com/44541702/218106754-8ad033ac-8699-4ee1-a3d4-6cab904bb784.png)

Burp版本 v2022.12.7
java版本 17.0.2

**Comment by f0ng** [comment]
根据代码逻辑，正常请求包应该不会此问题，host是直接用.和`getPort()`函数拼接的

<img width="773" alt="image" src="https://user-images.githubusercontent.com/48286013/218639302-f677b730-f366-485f-b248-ed692d25c038.png">

根据截图来看，情况应该是这样的，uri处也有完整域名请求:

<img width="668" alt="image" src="https://user-images.githubusercontent.com/48286013/218639726-30f668a3-312d-417f-a46c-4fc13bd668ce.png">

<img width="531" alt="image" src="https://user-images.githubusercontent.com/48286013/218639585-191d3eb5-ca91-4c63-8617-c953e990db65.png">

但是一般情况下，burp不会有uri处也有完整域名请求的情况

**Comment by f0ng** [comment]
`0.22.0`版本修复该问题
