### ISSUE TITLE
请把dnslog平台加白

### ISSUE THREAD

**Issue by yumusb** [f0ng/log4j2burpscanner#6]
目前收到很多来自你插件的无意义被动扫描，请把 咕.com (xn--9tr.com) 全局加白。感谢。

**Comment by f0ng** [comment]
师傅好，是什么样的扫描，能具体说说吗

**Comment by yumusb** [comment]
你插件中提示在浏览器去 /token 页面取结果。然后浏览器访问时候就把我网站加到被动扫描列表了。

**Comment by f0ng** [comment]
好的，将在下个版本加至白名单

**Comment by f0ng** [comment]
`0.14`版本已将dnslog地址加白

**Comment by yumusb** [comment]
//        if (host.equals("log.xn--9tr.com"))  貌似没加成功。

**Comment by f0ng** [comment]
好像是，哈哈，我给注释了，忘记了，0.15去掉注释，感谢反馈
