### ISSUE TITLE
建议同步下release中24.0的代码

### ISSUE THREAD

**Issue by heiha7789** [f0ng/log4j2burpscanner#60]
release zip中的代码未更新，还是2022-12-9之前的代码，未包含prefixparam字段

打包好的jar中包含该字段
![image](https://user-images.githubusercontent.com/57821098/233252916-eab3cd44-dac9-429e-8ea5-30c636d7dd72.png)
zip中的代码未包含该字段
![image](https://user-images.githubusercontent.com/57821098/233253242-f76f930b-aea0-487b-8047-9dc479be7896.png)

**Comment by f0ng** [comment]
`0.25.0`已同步
