### ISSUE TITLE
bug,设置自定义dns未生效，右键菜单Send to log4j2 Scanner 没反应

### ISSUE THREAD

**Issue by komomon** [f0ng/log4j2burpscanner#63]
bug,我使用的是vulhub本地搭建的环境测试的插件，设置自定义dns未生效，dns那边没有请求记录，右键菜单Send to log4j2 Scanner 没反应，dns那边也没有记录
还有个问题开启被动扫描，就会扫描每个请求包吗，还是只扫描某一类请求包

**Comment by f0ng** [comment]
1.关于这个问题可以看issue或者faq里有解答，设置问题，非bug
2.开启会扫描所有的包



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Komomon ***@***.***&gt;
发送时间: 2023年6月9日 21:46
收件人: f0ng/log4j2burpscanner ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [f0ng/log4j2burpscanner] bug,设置自定义dns未生效，右键菜单Send to log4j2 Scanner 没反应 (Issue #63)





 
bug,我使用的是vulhub本地搭建的环境测试的插件，设置自定义dns未生效，dns那边没有请求记录，右键菜单Send to log4j2 Scanner 没反应，dns那边也没有记录
 还有个问题开启被动扫描，就会扫描每个请求包吗，还是只扫描某一类请求包
