### ISSUE TITLE
Extender里发现漏洞命中有记录，但是在插件面板中为空

### ISSUE THREAD

**Issue by ShanRen995** [f0ng/log4j2burpscanner#64]

**Comment by ShanRen995** [comment]
作者大大好，发现在extender的output中可以看到漏洞命中的记录，dnslog平台上也确实收到了请求，但是在插件模块中没有看到记录返回
<img width="772" alt="image" src="https://github.com/f0ng/log4j2burpscanner/assets/84514302/cfa51947-7717-405d-b18e-834f9b621f5b">
<img width="1446" alt="image" src="https://github.com/f0ng/log4j2burpscanner/assets/84514302/3e562e5f-e4ad-4455-b60a-f8c0e52bf968">

**Comment by f0ng** [comment]
会有延迟的，这样说明是轮询查询模块得到了结果
