### ISSUE TITLE
send log4j 无效

### ISSUE THREAD

**Issue by lemonlove7** [f0ng/log4j2burpscanner#65]
<img width="848" alt="图片" src="https://github.com/f0ng/log4j2burpscanner/assets/56328995/b4e3ed92-bc2a-46d4-933d-c0cd1e0808e2">
<img width="1214" alt="图片" src="https://github.com/f0ng/log4j2burpscanner/assets/56328995/7f4f81af-a4f9-4069-b899-a6a6f7166fe7">

**Comment by ghghfgd** [comment]
我也有这个问题

**Comment by f0ng** [comment]
参考
https://github.com/f0ng/log4j2burpscanner/blob/main/FAQ-zh-CN.md#%E6%88%96%E8%80%85send-to-log4j2-scanner%E6%B2%A1%E6%9C%89%E5%8A%A8%E9%9D%99

**Comment by f0ng** [comment]
这里有漏洞才会显示，没有漏洞的话要去logger里看是否扫描
