### ISSUE TITLE
测试发现部分漏洞站点对jndi:dns://无反应

### ISSUE THREAD

**Issue by k-fire** [f0ng/log4j2burpscanner#9]
但是对jndi:ldap://有反应

**Comment by f0ng** [comment]
感谢师傅反馈，将在下个版本进行优化

**Comment by Chinakentgao** [comment]
> 感谢师傅反馈，将在下个版本进行优化
把rmi的格式也加入一下，漏洞系统的JDK版本关系到ldap和rmi的触发。可以参考下fastjson的利用工具

**Comment by f0ng** [comment]
`0.15`版本已经更新，可以自定义dns、ldap、或者rmi也可以
